((nil . ((indent-tabs-mode . nil)))
 (cperl-mode . ((cperl-indent-level . 4)
                (cperl-continued-statement-offset . 4)
                (cperl-continued-brace-offset . 0)
                (cperl-close-paren-offset . -4)
                (cperl-indent-subs-specially . nil)
                (indent-tabs-mode . nil))))
